CREATE TABLE ATIV (
  CD_ATIV int(3) NOT NULL,
  NM_SIGLA varchar(12),
  TX_DESCRICAO varchar(30),
  PRIMARY KEY (CD_ATIV));

CREATE TABLE DEPTO (
  CD_DEPTO char(3),
  NM_DEPTO varchar(40),
  CD_GERENTE int(5),
  PRIMARY KEY (CD_DEPTO));
  
  CREATE TABLE FUNC (
  CD_MAT int(5) NOT NULL,
  NM_FUNC varchar(12),
  NM_SOBRENOME varchar(12),
  CD_DEPTO char(3),
  NR_RAMAL int(4),
  DT_ADM date,
  NR_CARGO int(3),
  NR_RG int(2),
  IN_SEXO varchar(1),
  DT_NASC date,
  VL_SAL int(9),
  NM_FOTO varchar(100),
  PRIMARY KEY (`CD_MAT`),
  FOREIGN KEY (`CD_DEPTO`) REFERENCES DEPTO (`CD_DEPTO`));
  
  CREATE TABLE HST_PROMO (
  CD_MAT int(5) NOT NULL,
  CD_DEPTO char(3) NOT NULL,
  DT_PROMOCAO date,
  VL_SAL int(9),
  NR_CARGO int(3) NOT NULL,
  TX_MOTIVO varchar(200),
  PRIMARY KEY (CD_MAT,CD_DEPTO, NR_CARGO),
  FOREIGN KEY (CD_MAT) REFERENCES FUNC (CD_MAT),
  FOREIGN KEY (CD_DEPTO) REFERENCES DEPTO (CD_DEPTO)
);

CREATE TABLE PROJ (
  CD_PROJ char(6) NOT NULL,
  NM_PROJ varchar(30),
  CD_DEPTO char(3),
  CD_RESP int(5),
  QT_EQP int(2),
  DT_INI date,
  DT_FIM date,
  PRIMARY KEY (CD_PROJ),
  FOREIGN KEY (CD_DEPTO) REFERENCES DEPTO (CD_DEPTO)
);

CREATE TABLE PROJETO_ATIVIDADE (
  CD_PROJ char(6) NOT NULL,
  CD_ATIV int(3) NOT NULL,
  DT_INI date,
  DT_FIM date,
  PRIMARY KEY (CD_PROJ,CD_ATIV),
  FOREIGN KEY (CD_PROJ) REFERENCES PROJ (CD_PROJ)
) 